import type { Kysely } from "kysely";

const grapes = [
  "Agiorgitiko",
  "Aglianico",
  "Airen",
  "Albarino",
  "Alicante Bouschet",
  "Aligote",
  "Altesse",
  "Arinto",
  "Arneis",
  "Assyrtiko",
  "Baco Noir",
  "Baga",
  "Barbera",
  "Blaufrankisch",
  "Bobal",
  "Bonarda",
  "Bourboulenc",
  "Brachetto",
  "Cabernet Franc",
  "Cabernet Sauvignon",
  "Canaiolo",
  "Carignan",
  "Carmenere",
  "Castelao",
  "Catarratto",
  "Chardonnay",
  "Chasselas",
  "Chenin Blanc",
  "Cinsault",
  "Clairette",
  "Colombard",
  "Cortese",
  "Corvina",
  "Counoise",
  "Dolcetto",
  "Dornfelder",
  "Encruzado",
  "Erbaluce",
  "Falanghina",
  "Fernao Pires",
  "Fiano",
  "Frappato",
  "Friulano",
  "Fumin",
  "Furmint",
  "Gaglioppo",
  "Gamay",
  "Garganega",
  "Garnacha Blanca",
  "Gewurztraminer",
  "Glera",
  "Godello",
  "Graciano",
  "Grasevina",
  "Grechetto",
  "Greco",
  "Grenache",
  "Grenache Blanc",
  "Grillo",
  "Gros Manseng",
  "Gruner Veltliner",
  "Hondarrabi Zuri",
  "Kadarka",
  "Kekfrankos",
  "Lagrein",
  "Lambrusco",
  "Loureiro",
  "Macabeo",
  "Malbec",
  "Malvasia",
  "Malvasia Nera",
  "Manseng Noir",
  "Marselan",
  "Marsanne",
  "Mavrodaphne",
  "Melon de Bourgogne",
  "Mencia",
  "Merlot",
  "Monastrell",
  "Montepulciano",
  "Moscatel",
  "Moscato",
  "Mourvedre",
  "Muller-Thurgau",
  "Muscadet",
  "Muscat",
  "Muscat Blanc a Petits Grains",
  "Nebbiolo",
  "Negroamaro",
  "Nerello Cappuccio",
  "Nerello Mascalese",
  "Nero d'Avola",
  "Nero di Troia",
  "Nielluccio",
  "Nosiola",
  "Pais",
  "Palomino",
  "Pecorino",
  "Pedro Ximenez",
  "Petit Manseng",
  "Petit Verdot",
  "Petite Sirah",
  "Picpoul",
  "Pinot Blanc",
  "Pinot Grigio",
  "Pinot Gris",
  "Pinot Meunier",
  "Pinot Noir",
  "Pinotage",
  "Plavac Mali",
  "Primitivo",
  "Prosecco",
  "Refosco",
  "Ribolla Gialla",
  "Riesling",
  "Rolle",
  "Rondinella",
  "Roussanne",
  "Sagrantino",
  "Saint Laurent",
  "Sangiovese",
  "Saperavi",
  "Sauvignon Blanc",
  "Savagnin",
  "Scheurebe",
  "Schiava",
  "Sciaccarello",
  "Semillon",
  "Silvaner",
  "Syrah",
  "Tannat",
  "Tempranillo",
  "Teroldego",
  "Timorasso",
  "Tinta Roriz",
  "Torrontes",
  "Touriga Franca",
  "Touriga Nacional",
  "Trebbiano",
  "Trincadeira",
  "Trollinger",
  "Ugni Blanc",
  "Verdejo",
  "Verdicchio",
  "Verdelho",
  "Vermentino",
  "Vernaccia",
  "Vidal Blanc",
  "Viognier",
  "Viura",
  "Welschriesling",
  "Xinomavro",
  "Zierfandler",
  "Zinfandel",
  "Zweigelt",
];

export async function seed(db: Kysely<any>): Promise<void> {
  for (const name of grapes) {
    try {
      await db.insertInto("grape").values({ name }).execute();
    } catch {
      // duplicate, skip
    }
  }

  console.log(`Seeded ${grapes.length} grapes`);
}
