import type { Kysely } from "kysely";
import { env } from "@utils/env.js";

const regionsByCountry: Record<string, string[]> = {
  France: [
    "Alsace",
    "Beaujolais",
    "Bordeaux",
    "Burgundy",
    "Champagne",
    "Corsica",
    "Jura",
    "Languedoc-Roussillon",
    "Loire Valley",
    "Provence",
    "Rhone Valley",
    "Savoie",
    "Southwest France",
  ],
  Italy: [
    "Abruzzo",
    "Aosta Valley",
    "Basilicata",
    "Calabria",
    "Campania",
    "Emilia-Romagna",
    "Friuli-Venezia Giulia",
    "Lazio",
    "Liguria",
    "Lombardy",
    "Marche",
    "Molise",
    "Piedmont",
    "Puglia",
    "Sardinia",
    "Sicily",
    "Trentino-Alto Adige",
    "Tuscany",
    "Umbria",
    "Veneto",
  ],
  Spain: [
    "Bierzo",
    "Calatayud",
    "Campo de Borja",
    "Catalonia",
    "Cigales",
    "Costers del Segre",
    "Jerez",
    "Jumilla",
    "La Mancha",
    "Mallorca",
    "Manchuela",
    "Montsant",
    "Navarra",
    "Penedes",
    "Priorat",
    "Rias Baixas",
    "Ribeira Sacra",
    "Ribera del Duero",
    "Rioja",
    "Rueda",
    "Somontano",
    "Terra Alta",
    "Toro",
    "Txakoli",
    "Utiel-Requena",
    "Valencia",
    "Yecla",
  ],
  Portugal: [
    "Alentejo",
    "Algarve",
    "Bairrada",
    "Dao",
    "Douro Valley",
    "Lisboa",
    "Madeira",
    "Minho",
    "Setubal",
    "Tejo",
    "Tras-os-Montes",
  ],
  Germany: [
    "Ahr",
    "Baden",
    "Franconia",
    "Hessische Bergstrasse",
    "Mittelrhein",
    "Mosel",
    "Nahe",
    "Pfalz",
    "Rheingau",
    "Rheinhessen",
    "Saale-Unstrut",
    "Saxony",
    "Wurttemberg",
  ],
  Austria: [
    "Burgenland",
    "Carnuntum",
    "Kamptal",
    "Kremstal",
    "Neusiedlersee",
    "Styria",
    "Thermenregion",
    "Traisental",
    "Vienna",
    "Wachau",
    "Wagram",
    "Weinviertel",
  ],
  "United States": [
    "Alexander Valley",
    "Anderson Valley",
    "Carneros",
    "Central Coast",
    "Columbia Valley",
    "Dry Creek Valley",
    "Finger Lakes",
    "Horse Heaven Hills",
    "Livermore Valley",
    "Lodi",
    "Long Island",
    "Monterey",
    "Napa Valley",
    "Paso Robles",
    "Red Mountain",
    "Russian River Valley",
    "Santa Barbara County",
    "Santa Cruz Mountains",
    "Santa Maria Valley",
    "Santa Rita Hills",
    "Santa Ynez Valley",
    "Sonoma Coast",
    "Sonoma Valley",
    "Stags Leap District",
    "Temecula Valley",
    "Virginia",
    "Walla Walla Valley",
    "Willamette Valley",
    "Yakima Valley",
  ],
  Australia: [
    "Adelaide Hills",
    "Barossa Valley",
    "Beechworth",
    "Clare Valley",
    "Coonawarra",
    "Eden Valley",
    "Geelong",
    "Granite Belt",
    "Great Southern",
    "Heathcote",
    "Hunter Valley",
    "King Valley",
    "Langhorne Creek",
    "Margaret River",
    "McLaren Vale",
    "Mornington Peninsula",
    "Mudgee",
    "Orange",
    "Padthaway",
    "Riverina",
    "Rutherglen",
    "Swan Valley",
    "Tasmania",
    "Yarra Valley",
  ],
  "New Zealand": [
    "Auckland",
    "Canterbury",
    "Central Otago",
    "Gisborne",
    "Hawke's Bay",
    "Marlborough",
    "Martinborough",
    "Nelson",
    "Northland",
    "Waiheke Island",
    "Waipara Valley",
    "Wairarapa",
  ],
  Argentina: [
    "Cafayate",
    "Catamarca",
    "La Rioja",
    "Lujan de Cuyo",
    "Maipu",
    "Mendoza",
    "Neuquen",
    "Patagonia",
    "Rio Negro",
    "Salta",
    "San Juan",
    "Uco Valley",
  ],
  Chile: [
    "Aconcagua Valley",
    "Bio Bio Valley",
    "Cachapoal Valley",
    "Casablanca Valley",
    "Choapa Valley",
    "Colchagua Valley",
    "Curico Valley",
    "Elqui Valley",
    "Itata Valley",
    "Leyda Valley",
    "Limari Valley",
    "Maipo Valley",
    "Malleco Valley",
    "Maule Valley",
    "Rapel Valley",
    "San Antonio Valley",
  ],
  "South Africa": [
    "Breedekloof",
    "Cape South Coast",
    "Constantia",
    "Darling",
    "Durbanville",
    "Elgin",
    "Franschhoek",
    "Hemel-en-Aarde",
    "Paarl",
    "Robertson",
    "Stellenbosch",
    "Swartland",
    "Tulbagh",
    "Walker Bay",
    "Wellington",
    "Worcester",
  ],
  Greece: [
    "Cephalonia",
    "Crete",
    "Drama",
    "Macedonia",
    "Naoussa",
    "Nemea",
    "Peloponnese",
    "Santorini",
    "Thessaly",
  ],
  Hungary: ["Eger", "Somlo", "Szekszard", "Tokaj", "Villany"],
  Croatia: ["Croatian Uplands", "Dalmatia", "Istria", "Kvarner", "Slavonia"],
  Georgia: ["Imereti", "Kakheti", "Kartli", "Racha-Lechkhumi"],
  Switzerland: ["Geneva", "Ticino", "Valais", "Vaud"],
  Lebanon: ["Bekaa Valley"],
  Israel: [
    "Galilee",
    "Golan Heights",
    "Judean Hills",
    "Negev",
    "Samson",
    "Shomron",
  ],
  Canada: [
    "British Columbia",
    "Niagara Peninsula",
    "Nova Scotia",
    "Prince Edward County",
  ],
  Romania: ["Dealu Mare", "Moldova", "Murfatlar", "Transylvania"],
  Bulgaria: [
    "Danube Plain",
    "Rose Valley",
    "Struma Valley",
    "Thracian Lowlands",
  ],
  Slovenia: [
    "Goriska Brda",
    "Podravje",
    "Posavje",
    "Primorska",
    "Vipava Valley",
  ],
  Turkey: ["Aegean", "Cappadocia", "Eastern Anatolia", "Thrace"],
  Uruguay: ["Canelones", "Colonia", "Maldonado", "Montevideo", "Rivera"],
  Brazil: ["Campanha", "Serra Gaucha", "Vale do Sao Francisco"],
  "United Kingdom": ["Hampshire", "Kent", "Surrey", "Sussex"],
  Mexico: ["Baja California", "Coahuila", "Queretaro"],
  Moldova: ["Codru", "Purcari", "Stefan Voda", "Valul lui Traian"],
  China: ["Ningxia", "Shandong", "Xinjiang", "Yunnan"],
  Japan: ["Hokkaido", "Nagano", "Yamagata", "Yamanashi"],
  India: ["Karnataka", "Maharashtra"],
};

export async function seed(db: Kysely<any>): Promise<void> {
  let regionCount = 0;

  for (const [countryName, regions] of Object.entries(regionsByCountry)) {
    const country = await db
      .selectFrom("country")
      .select("id")
      .where("name", "=", countryName)
      .executeTakeFirst();

    if (!country) {
      console.log(`Skipping regions for "${countryName}" (country not found)`);
      continue;
    }

    for (const regionName of regions) {
      const query = db
        .insertInto("region")
        .values({ name: regionName, countryId: country.id });
      await (
        env.DATABASE_TYPE === "mysql"
          ? query.ignore()
          : query.onConflict((oc) =>
              oc.columns(["name", "countryId"]).doNothing(),
            )
      ).execute();
      regionCount++;
    }
  }

  console.log(
    `Seeded ${regionCount} regions across ${Object.keys(regionsByCountry).length} countries`,
  );
}
