name: PR Checks

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  statuses: write

jobs:
  tests:
    name: Tests
    if: github.event.pull_request.draft == false
    uses: ./.github/workflows/ci-tests.yml
    with:
      detect-changes: true
      upload-coverage: true
