name: PR Labeler & Release Draft

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  label:
    name: Autolabel & Update Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: release-drafter/release-drafter/autolabeler@5de93583980a40bd78603b6dfdcda5b4df377b32 # v7.2.0
        if: github.event_name == 'pull_request_target'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
