name: PR Labeler & Release Draft

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  label:
    name: Autolabel & Update Draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@00ce30b0ce8a4d67bccfca59421cdf6c55dd0784 # v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
